name: Second CI # This is the second workflow that runs on push events to the main branch

on: # This workflow is triggered on push events to the main branch
  # push
   workflow_dispatch:

jobs: # This defines the jobs for the workflow
  build:
    runs-on: ubuntu-latest

    steps: # This defines the steps for the build job
      - name: Say Hello
        run: echo 'Hello from the second workflow!'

