name: Second CI

on: # This workflow is triggered on push events to the main branch
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo 'Hello from the second workflow!'

